Add pr_comment.sh and store copy of shell output (#79)
* Add pr_comment.sh and store copy of shell output

Fixes #38

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -33,7 +33,7 @@ jobs:
           command: |
             sudo apt-get install default-mysql-client
             mysql -h 127.0.0.1 -u username -pp4ssw0rd -e 'CREATE DATABASE IF NOT EXISTS updatebot;'
-          name: Install MySQL CLI; Create updatebot db and localconfig
+          name: Create updatebot database
       - save_cache:
           key: deps-{{ checksum "poetry.lock" }}
           paths:
@@ -64,9 +64,24 @@ jobs:
             echo Failed waiting for MySQL && exit 1
           name: Waiting for MySQL to be ready
       - run:
+          # The if/else clause simulates a try/catch block in bash due to
+          # CircleCI halting as soon as any command returns a non-zero value.
+          # COMMAND_OUTPUT ends up being stdout and stderr for the command run
+          # and the if statement checks poetry's return value.
+          #
+          # This ensures that the pr_comment script is run regardless of if our
+          # command fails.
           command: |
+            sudo apt-get install jq
             cp localconfig.py.example localconfig.py
-            poetry run coverage run test.py
+            if COMMAND_OUTPUT=$(poetry run coverage run test.py 2>&1); then
+              echo $COMMAND_OUTPUT
+            else
+              echo $COMMAND_OUTPUT
+              COMMAND_OUTPUT=$(jq -nc --arg str "$COMMAND_OUTPUT" '$str')
+              . .circleci/pr_comment.sh
+              exit 1
+            fi
           name: test
       - run:
           command: poetry run codecov
@@ -83,7 +98,23 @@ jobs:
           command: poetry check
           name: dependencies
       - run:
-          command: poetry run flake8 --ignore=E501,E402 .
+          # The if/else clause simulates a try/catch block in bash due to
+          # CircleCI halting as soon as any command returns a non-zero value.
+          # COMMAND_OUTPUT ends up being stdout and stderr for the command run
+          # and the if statement checks poetry's return value.
+          #
+          # This ensures that the pr_comment script is run regardless of if our
+          # command fails.
+          command: |
+            sudo apt-get install jq
+            if COMMAND_OUTPUT=$(poetry check && poetry run flake8 --ignore=E501,E402 . 2>&1); then
+              echo $COMMAND_OUTPUT
+            else
+              echo $COMMAND_OUTPUT
+              COMMAND_OUTPUT=$(jq -nc --arg str "$COMMAND_OUTPUT" '$str')
+              . .circleci/pr_comment.sh
+              exit 1
+            fi
           name: lint
 
   cleanup:
